-- ============================================
-- SEED: Datos iniciales
-- ============================================
-- Este archivo está vacío.
-- Los datos deben crearse directamente en la base de datos.
-- ============================================
